// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoS92zRSI7_DAjtoLQ13Jq02_iBAnOfkQ',
    appId: '1:555736858076:web:18e91706d0c3120b402319',
    messagingSenderId: '555736858076',
    projectId: 'triageia-18fd9',
    authDomain: 'triageia-18fd9.firebaseapp.com',
    storageBucket: 'triageia-18fd9.firebasestorage.app',
    measurementId: 'G-80XQ5TZQ06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxuWAoKo_IaTQaeT90ZNwb3XW2AR95NjE',
    appId: '1:555736858076:android:abe81862818bb55a402319',
    messagingSenderId: '555736858076',
    projectId: 'triageia-18fd9',
    storageBucket: 'triageia-18fd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBycurYCxAuFIOm2oNx0v2Q-uQM2au6U5A',
    appId: '1:555736858076:ios:93467fc71d3942aa402319',
    messagingSenderId: '555736858076',
    projectId: 'triageia-18fd9',
    storageBucket: 'triageia-18fd9.firebasestorage.app',
    iosBundleId: 'com.example.triageAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBycurYCxAuFIOm2oNx0v2Q-uQM2au6U5A',
    appId: '1:555736858076:ios:93467fc71d3942aa402319',
    messagingSenderId: '555736858076',
    projectId: 'triageia-18fd9',
    storageBucket: 'triageia-18fd9.firebasestorage.app',
    iosBundleId: 'com.example.triageAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoS92zRSI7_DAjtoLQ13Jq02_iBAnOfkQ',
    appId: '1:555736858076:web:318f91610f747f6d402319',
    messagingSenderId: '555736858076',
    projectId: 'triageia-18fd9',
    authDomain: 'triageia-18fd9.firebaseapp.com',
    storageBucket: 'triageia-18fd9.firebasestorage.app',
    measurementId: 'G-GJ1Y16P73G',
  );

}